# Generated by Django 4.2 on 2024-06-13 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plazos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plazo_Fijo',
            new_name='PlazoFijo',
        ),
    ]
