# Generated by Django 4.2 on 2024-06-13 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plazos', '0002_rename_plazo_fijo_plazofijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plazofijo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
