# Generated by Django 4.2 on 2024-06-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plazos', '0004_alter_entidad_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='tipo',
            field=models.CharField(choices=[('Deposito', 'Depósito'), ('Retiro', 'Retiro'), ('Interes', 'Interés')], default='Deposito', max_length=10),
            preserve_default=False,
        ),
    ]
