# Generated by Django 4.2 on 2024-06-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plazos', '0005_operacion_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidad',
            old_name='plazo_fijo',
            new_name='plazo',
        ),
    ]
