# Generated by Django 4.2 on 2024-06-14 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plazos', '0006_rename_plazo_fijo_entidad_plazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='monto',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
