name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
        name: Deploy Server-Martin

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/plazos-compartidos:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
        name: Deploy Server-Martin

    steps:
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/plazos-compartidos-api:latest
            docker stop plazos-compartidos-api || true
            docker rm plazos-compartidos-api || true
            docker network connect mysql-red plazos-compartidos-api || true
            docker run -d \
              --name plazos-compartidos-api \
              --restart unless-stopped \
              --network mysql-red \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              -e DB_HOST=MySQL \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -p 8888:8888 \
              ${{ secrets.DOCKER_USERNAME }}/plazos-compartidos-api:latest