name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Deploy Server-Martin

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push api image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.api
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/plazos-compartidos-api:latest

    - name: Build and push cron image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.cron
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/plazos-compartidos-cron:latest

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Server
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/plazos-compartidos-cron:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/plazos-compartidos-api:latest

          docker stop plazos-compartidos-cron || true
          docker stop plazos-compartidos-api || true
          docker rm plazos-compartidos-cron || true
          docker rm plazos-compartidos-api || true

          docker run -d --restart unless-stopped \
            --name plazos-compartidos-api \
            --env SECRET_KEY=${{ secrets.SECRET_KEY }} \
            --env DB_HOST=MySQL \
            --env DB_NAME=${{ secrets.DB_NAME }} \
            --env DB_USER=${{ secrets.DB_USER }} \
            --env DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --env DB_PORT=${{ secrets.DB_PORT }} \
            --env TZ="America/Argentina/Buenos_Aires" \
            --network "mysql -red" \
            -v plazos-compartidos-data:"/app" \
            -v SSL_Certificados:"/app/certs" \
            -p 8888:8888 \
            1pampu/plazos-compartidos-api:latest

          docker run -d --restart unless-stopped \
            --name plazos-compartidos-cron \
            --env SECRET_KEY=${{ secrets.SECRET_KEY }} \
            --env DB_HOST=${{ secrets.DB_HOST }} \
            --env DB_NAME=${{ secrets.DB_NAME }} \
            --env DB_USER=${{ secrets.DB_USER }} \
            --env DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --env DB_PORT=${{ secrets.DB_PORT }} \
            --env TZ="America/Argentina/Buenos_Aires" \
            --network "mysql -red" \
            -v plazos-compartidos-data:"/app" \
            1pampu/plazos-compartidos-cron:latest
        EOF