name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Deploy Server-Martin

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t plazos-compartidos-api:latest .
        docker tag plazos-compartidos-api:latest ${{ secrets.DOCKER_USERNAME }}/plazos-compartidos-api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/plazos-compartidos-api:latest

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Server
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/plazos-compartidos-api:latest
          docker stop plazos-compartidos-api || true
          docker rm plazos-compartidos-api || true
          docker run -d --restart unless-stopped \
            --name plazos-compartidos-api \
            --env SECRET_KEY=${{ secrets.SECRET_KEY }} \
            --env DB_HOST=MySQL \
            --env DB_NAME=${{ secrets.DB_NAME }} \
            --env DB_USER=${{ secrets.DB_USER }} \
            --env DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --env DB_PORT=${{ secrets.DB_PORT }} \
            --network "mysql -red" \
            -v "${{ secrets.SSL_PATH }}":"/SSL" \
            1pampu/plazos-compartidos-api:latest
        EOF